### ISSUE TITLE
如何禁止进度条滑动呢

### ISSUE THREAD

**Issue by yjt1216** [war1644/fijkplayer_skin#1]
我将水平方向进度条 全部禁止滑动了，但是还能滑动

**Comment by ggdream** [comment]
#### 临时解决办法：
1. 在这个Widget里添加一个是否能滑动的参数：
https://github.com/war1644/fijkplayer_skin/blob/8efcec68bbc8c3d3220b12c5281d958dd1979077/lib/slider.dart#L9-L38
2. 在这里判断参数，不允许就直接reture：
https://github.com/war1644/fijkplayer_skin/blob/8efcec68bbc8c3d3220b12c5281d958dd1979077/lib/slider.dart#L71-L81
